import = [
  # Colour scheme.
  "~/.config/alacritty/solarized-osaka.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "SF Mono", style = "Regular" }
size = 14.0

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

# Japanese keyboards have a ¥ key, and \ is input via Option-¥.
# Swap the mappings in the terminal for convenience when coding.
[[keyboard.bindings]]
chars="\\"
key = "¥"
[[keyboard.bindings]]
chars="¥"
key = "¥"
mods = "Alt"
