# Colors (Solarized Osaka)

[colors.primary]
background = '#222334'
foreground = '#cad2f2'

[colors.cursor]
cursor = '#cad2f2'
text = '#222334'

[colors.selection]
background = '#303e72'
text = '#cad2f2'

[colors.search.matches]
foreground = '#1b1c29'
background = '#f6c982'

[colors.search.focused_match]
foreground = '#1b1c29'
background = '#ffff00'

[colors.normal]
black   = '#1b1c29'
red     = '#ed7d81'
green   = '#cae697'
yellow  = '#f6c982'
blue    = '#8aa8f8'
magenta = '#b99af8'
cyan    = '#9bdef8'
white   = '#838ab4'

[colors.bright]
black   = '#454970'
red     = '#ed7d81'
green   = '#cae697'
yellow  = '#f6c982'
blue    = '#8aa8f8'
magenta = '#b99af8'
cyan    = '#9bdef8'
white   = '#cad2f2'
